let ms = {
    cars: [
        {
            "Maker": "Bentley",
            "Genmodel": "Arnage",
            "Genmodel_ID": "10_1",
            "Adv_ID": "10_1$$27",
            "Adv_year": 2018,
            "Adv_month": 3,
            "Color": "Green",
            "Reg_year": 2000,
            "Bodytype": "Saloon",
            "Runned_Miles": 30000,
            "Engin_size": "6.8L",
            "Gearbox": "Automatic",
            "Fuel_type": "Petrol",
            "Price": 29950,
            "Seat_num": 5,
            "Door_num": 4
        },
        {
            "Maker": "Bentley",
            "Genmodel": "Bentayga",
            "Genmodel_ID": "10_3",
            "Adv_ID": "10_3$$7",
            "Adv_year": 2018,
            "Adv_month": 8,
            "Color": "Grey",
            "Reg_year": 2017,
            "Bodytype": "SUV",
            "Runned_Miles": 10972,
            "Engin_size": "6.0L",
            "Gearbox": "Automatic",
            "Fuel_type": "Petrol",
            "Price": 139950,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Bentley",
            "Genmodel": "Bentayga",
            "Genmodel_ID": "10_3",
            "Adv_ID": "10_3$$14",
            "Adv_year": 2018,
            "Adv_month": 6,
            "Color": "Blue",
            "Reg_year": 2016,
            "Bodytype": "SUV",
            "Runned_Miles": 5900,
            "Engin_size": "6.0L",
            "Gearbox": "Automatic",
            "Fuel_type": "Petrol",
            "Price": 139900,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Chevrolet",
            "Genmodel": "Matiz",
            "Genmodel_ID": "16_12",
            "Adv_ID": "16_12$$77",
            "Adv_year": 2018,
            "Adv_month": 5,
            "Color": "Blue",
            "Reg_year": 2006,
            "Bodytype": "Hatchback",
            "Runned_Miles": 74800,
            "Engin_size": "0.8L",
            "Gearbox": "Manual",
            "Fuel_type": "Petrol",
            "Price": 460,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Chrysler",
            "Genmodel": "300C",
            "Genmodel_ID": "17_1",
            "Adv_ID": "17_1$$16",
            "Adv_year": 2018,
            "Adv_month": 4,
            "Color": "Black",
            "Reg_year": 2007,
            "Bodytype": "Estate",
            "Runned_Miles": 157950,
            "Engin_size": "5.7L",
            "Gearbox": "Automatic",
            "Fuel_type": "Petrol",
            "Price": 5495,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Citroen",
            "Genmodel": "C3 Picasso",
            "Genmodel_ID": "18_10",
            "Adv_ID": "18_10$$92",
            "Adv_year": 2018,
            "Adv_month": 6,
            "Color": "Beige",
            "Reg_year": 2009,
            "Bodytype": "MPV",
            "Runned_Miles": 99000,
            "Engin_size": "1.6L",
            "Gearbox": "Manual",
            "Fuel_type": "Diesel",
            "Price": 1490,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Citroen",
            "Genmodel": "C4 Cactus",
            "Genmodel_ID": "18_13",
            "Adv_ID": "18_13$$53",
            "Adv_year": 2018,
            "Adv_month": 1,
            "Color": "Yellow",
            "Reg_year": 2016,
            "Bodytype": "Hatchback",
            "Runned_Miles": 10967,
            "Engin_size": "1.6L",
            "Gearbox": "Manual",
            "Fuel_type": "Diesel",
            "Price": 10495,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Fiat",
            "Genmodel": "Tipo",
            "Genmodel_ID": "28_28",
            "Adv_ID": "28_28$$22",
            "Adv_year": 2018,
            "Adv_month": 8,
            "Color": "White",
            "Reg_year": 2016,
            "Bodytype": "Estate",
            "Runned_Miles": 7000,
            "Engin_size": "1.4L",
            "Gearbox": "Manual",
            "Fuel_type": "Petrol",
            "Price": 10490,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Ford",
            "Genmodel": "Kuga",
            "Genmodel_ID": "29_25",
            "Adv_ID": "29_25$$609",
            "Adv_year": 2018,
            "Adv_month": 2,
            "Color": "Silver",
            "Reg_year": 2013,
            "Bodytype": "SUV",
            "Runned_Miles": 62003,
            "Engin_size": "2.0L",
            "Gearbox": "Manual",
            "Fuel_type": "Diesel",
            "Price": 10480,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Infiniti",
            "Genmodel": "Q70",
            "Genmodel_ID": "37_8",
            "Adv_ID": "37_8$$13",
            "Adv_year": 2018,
            "Adv_month": 4,
            "Color": "Grey",
            "Reg_year": 2017,
            "Bodytype": "Saloon",
            "Runned_Miles": 11562,
            "Engin_size": "2.1L",
            "Gearbox": "Automatic",
            "Fuel_type": "Diesel",
            "Price": 21000,
            "Seat_num": "",
            "Door_num": ""
        },
        {
            "Maker": "Mazda",
            "Genmodel": "CX-5",
            "Genmodel_ID": "57_7",
            "Adv_ID": "57_7$$313",
            "Adv_year": 2018,
            "Adv_month": 4,
            "Color": "Red",
            "Reg_year": 2017,
            "Bodytype": "SUV",
            "Runned_Miles": 6909,
            "Engin_size": "2.2L",
            "Gearbox": "Automatic",
            "Fuel_type": "Diesel",
            "Price": 20000,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Nissan",
            "Genmodel": "Pulsar",
            "Genmodel_ID": "64_32",
            "Adv_ID": "64_32$$666",
            "Adv_year": 2018,
            "Adv_month": 3,
            "Color": "Blue",
            "Reg_year": 2016,
            "Bodytype": "Hatchback",
            "Runned_Miles": 11875,
            "Engin_size": "1.5L",
            "Gearbox": "Manual",
            "Fuel_type": "Diesel",
            "Price": 9997,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Peugeot",
            "Genmodel": 207,
            "Genmodel_ID": "69_9",
            "Adv_ID": "69_9$$200",
            "Adv_year": 2018,
            "Adv_month": 4,
            "Color": "Black",
            "Reg_year": 2008,
            "Bodytype": "Hatchback",
            "Runned_Miles": 64000,
            "Engin_size": "1.4L",
            "Gearbox": "Manual",
            "Fuel_type": "Petrol",
            "Price": 1995,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "SEAT",
            "Genmodel": "Leon",
            "Genmodel_ID": "79_10",
            "Adv_ID": "79_10$$27",
            "Adv_year": 2018,
            "Adv_month": 5,
            "Color": "Black",
            "Reg_year": 2010,
            "Bodytype": "Hatchback",
            "Runned_Miles": 70567,
            "Engin_size": "1.4L",
            "Gearbox": "Manual",
            "Fuel_type": "Petrol",
            "Price": 4389,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Audi",
            "Genmodel": "Q5",
            "Genmodel_ID": "7_20",
            "Adv_ID": "7_20$$933",
            "Adv_year": 2018,
            "Adv_month": 7,
            "Color": "Grey",
            "Reg_year": 2013,
            "Bodytype": "SUV",
            "Runned_Miles": 48759,
            "Engin_size": "2.0L",
            "Gearbox": "Automatic",
            "Fuel_type": "Diesel",
            "Price": 19800,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "SKODA",
            "Genmodel": "Fabia",
            "Genmodel_ID": "80_2",
            "Adv_ID": "80_2$$653",
            "Adv_year": 2018,
            "Adv_month": 5,
            "Color": "Maroon",
            "Reg_year": 2009,
            "Bodytype": "Estate",
            "Runned_Miles": 83000,
            "Engin_size": "1.4L",
            "Gearbox": "Manual",
            "Fuel_type": "Diesel",
            "Price": 2650,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "BMW",
            "Genmodel": "M4",
            "Genmodel_ID": "8_31",
            "Adv_ID": "8_31$$210",
            "Adv_year": 2018,
            "Adv_month": 4,
            "Color": "Grey",
            "Reg_year": 2015,
            "Bodytype": "Coupe",
            "Runned_Miles": 32000,
            "Engin_size": "3.0L",
            "Gearbox": "Automatic",
            "Fuel_type": "Petrol",
            "Price": 39345,
            "Seat_num": 4,
            "Door_num": 2
        },
        {
            "Maker": "Toyota",
            "Genmodel": "Auris",
            "Genmodel_ID": "92_3",
            "Adv_ID": "92_3$$1713",
            "Adv_year": 2018,
            "Adv_month": 1,
            "Color": "White",
            "Reg_year": 2008,
            "Bodytype": "Hatchback",
            "Runned_Miles": 95000,
            "Engin_size": "2.2L",
            "Gearbox": "Manual",
            "Fuel_type": "Diesel",
            "Price": 3895,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Volkswagen",
            "Genmodel": "Golf",
            "Genmodel_ID": "95_15",
            "Adv_ID": "95_15$$1568",
            "Adv_year": 2018,
            "Adv_month": 4,
            "Color": "Blue",
            "Reg_year": 2008,
            "Bodytype": "Hatchback",
            "Runned_Miles": 130000,
            "Engin_size": "1.6L",
            "Gearbox": "Manual",
            "Fuel_type": "Petrol",
            "Price": 2695,
            "Seat_num": 5,
            "Door_num": 5
        },
        {
            "Maker": "Volvo",
            "Genmodel": "XC90",
            "Genmodel_ID": "96_18",
            "Adv_ID": "96_18$$376",
            "Adv_year": 2018,
            "Adv_month": 8,
            "Color": "Black",
            "Reg_year": 2012,
            "Bodytype": "SUV",
            "Runned_Miles": 51000,
            "Engin_size": "2.4L",
            "Gearbox": "Automatic",
            "Fuel_type": "Diesel",
            "Price": 17995,
            "Seat_num": 7,
            "Door_num": 5
        }
    ]
}

// only necessary when placing this variable in its own js file.
exports.msDB = ms;
